import Head from 'next/head'
import {useEffect, useState} from "react";

export default function ListTable({ data_output }) {

    // console.log("data_output",data_output.length)


    return (
        <div>
            <Head>
                <title>List Table</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div>
                    {getList(data_output)}
                </div>
            </main>
        </div>
    )


    function getList(data)
    {

        // hint_show_webservice_result_on_list
        const items = data.map((todo, index) =>
            <li key={index} style={{marginBottom:"3px"}}>
                {todo.id} - {todo.title} -
                {/*hint_button_on_list*/}
                <button onClick={ () => buttonClicked(todo) } style={{marginLeft:"10px"}}>
                    Inquiry Detail
                </button>
            </li>
        )
        return items
    }

    function buttonClicked(item)
    {
        // hint_show_detail_item_on_alert
        alert(item.id + " - " + item.title)
    }


}

// export async function getServerSideProps() {
//     const url1 = "https://jsonplaceholder.typicode.com/albums"
//     const res = await fetch(url1)
//     const data_output = await res.json()
//
//     // console.log("getServerSideProps",data_output)
//
//     return { props: { data_output } }
// }

export async function getStaticProps(context) {
    const url1 = "https://jsonplaceholder.typicode.com/albums"
    const res = await fetch(url1)
    const data_output = await res.json()

    // console.log("getStaticProps",data_output)

    return { props: { data_output } }
}

